# Generated by Django 5.2.1 on 2025-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_post1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
